
# Example binaries
cc_binary(
    name = "actor_agent_example",
    srcs = ["actor_agent_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "autonomous_agent_example",
    srcs = ["autonomous_agent_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "coroutine_example",
    srcs = ["coroutine_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "evaluator_optimizer_example",
    srcs = ["evaluator_optimizer_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "multimodal_example",
    srcs = ["multimodal_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "orchestrator_example",
    srcs = ["orchestrator_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "parallel_example",
    srcs = ["parallel_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "prompt_chain_example",
    srcs = ["prompt_chain_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "robotics_object_detection_demo",
    srcs = ["robotics_object_detection_demo.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "routing_example",
    srcs = ["routing_example.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "simple_agent",
    srcs = ["simple_agent.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "streaming_chat",
    srcs = ["streaming_chat.cpp"],
    deps = ["//:agents_cpp"],
)
cc_binary(
    name = "structured_output_example",
    srcs = ["structured_output_example.cpp"],
    deps = ["//:agents_cpp"],
)